export const ADD_INVENTORY = "ADD_INVENTORY";
export const DELETE_INVENTORY = "DELETE_INVENTORY";
export const UPDATE_INVENTORY = "UPDATE_INVENTORY";
export const FETCH_INVENTORY = "FETCH_INVENTORY";

export const FETCH_SALES = "FETCH_SALES";
export const ADD_SALES = "POST_SALES";

export const FAILED_OPERATION = "FAILED_OPERATION";
